-- IMS subscription and feature schema
-- Target: PostgreSQL 17+
--
-- Hybrid storage note:
-- 1. PostgreSQL stores organization, subscription, plan, feature catalog,
--    plan entitlements, plan selection rules, restrictions, organization
--    selections, coupons, employee/access taxonomy, and LDAP integration data.
-- 2. MongoDB stores the feature adjacency graph only.
-- 3. Organization-owned employee and access taxonomy stays table-driven,
--    not enum-driven, so each organization can define its own designations,
--    employment types, employment statuses, teams, resolver groups,
--    and permission groups.
-- 4. LDAP is treated as a first-class enterprise integration domain:
--    ldap_directory / ldap_group / ldap_user capture external directory state,
--    while mapping tables connect that state to the internal access model.
-- 5. Organization access assignment policy is explicit:
--    INTERNAL => direct employee assignment is primary
--    LDAP     => directory-derived assignment is primary
--    HYBRID   => LDAP-derived grants UNION manual grants MINUS employee-specific exclusions
--
-- Optional database creation (run separately as a superuser if needed):
-- CREATE DATABASE ims_subscription;
--
-- Then connect to the database before running the rest of this script.

-- Feature catalog examples:
-- 1  TKT_PAGE
-- 2  COMMENT_SECTION
-- 3  SUBJECT
-- 4  DESCRIPTION
-- 5  AUTO_TKT_RESOLUTION
-- 6  COMMENT_RES
-- 7  AI_SUBJECT_SUMMARY
-- 8  AUTH
-- 9  AUTH_TYPE_OAUTH
-- 10 AUTH_PROVIDER_GOOGLE
--
-- MongoDB adjacency examples:
-- 1  -> [2,3,4,5,7]
-- 2  -> [6]
-- 8  -> [9,11,12]
-- 9  -> [10,13,14]
-- 11 -> [15]

CREATE TYPE organization_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE domain_status AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE subscription_status AS ENUM ('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED');
CREATE TYPE billing_period AS ENUM ('MONTHLY', 'YEARLY');
CREATE TYPE discount_type AS ENUM ('PERCENTAGE', 'FIXED');
CREATE TYPE organization_feature_selection_status AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE exclusion_status AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE restriction_type AS ENUM ('BOOLEAN', 'NUMERIC', 'TEXT', 'DURATION');
CREATE TYPE restriction_operator AS ENUM ('EQ', 'NE', 'LT', 'LTE', 'GT', 'GTE', 'IN');
CREATE TYPE restriction_unit AS ENUM ('COUNT', 'DAY', 'MINUTE', 'FLAG', 'CHARACTER', 'PERCENT');
CREATE TYPE selection_scope AS ENUM ('DIRECT_CHILDREN');
CREATE TYPE feature_grant_type AS ENUM ('DIRECT', 'SELECTABLE');
CREATE TYPE ldap_identity_link_type AS ENUM ('PRIMARY', 'SECONDARY', 'ADMIN_ACCOUNT', 'SERVICE_ACCOUNT', 'HISTORICAL');
CREATE TYPE organization_access_mode AS ENUM ('INTERNAL', 'LDAP', 'HYBRID');

CREATE TABLE IF NOT EXISTS organization (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code VARCHAR(64) NOT NULL UNIQUE,
    organization_name VARCHAR(255) NOT NULL,
    status organization_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organization_access_policy (
    organization_access_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    access_mode organization_access_mode NOT NULL DEFAULT 'INTERNAL',
    allow_manual_permission_assignment BOOLEAN NOT NULL DEFAULT TRUE,
    allow_manual_resolver_assignment BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_org_access_policy_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_org_access_policy_org UNIQUE (organization_id)
);

CREATE TABLE IF NOT EXISTS organization_domain (
    organization_domain_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    domain_name VARCHAR(320) NOT NULL UNIQUE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    status domain_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at TIMESTAMP NULL,
    CONSTRAINT fk_org_domain_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id)
);

CREATE INDEX IF NOT EXISTS idx_org_domain_primary
    ON organization_domain (organization_id, is_primary);

CREATE TABLE IF NOT EXISTS designation (
    designation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    designation_code VARCHAR(64),
    designation_title VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_designation_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_designation_org_title UNIQUE (organization_id, designation_title),
    CONSTRAINT uk_designation_org_code UNIQUE (organization_id, designation_code)
);

CREATE TABLE IF NOT EXISTS employment_type (
    employment_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    type_key VARCHAR(64) NOT NULL,
    type_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employment_type_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_employment_type_org_key UNIQUE (organization_id, type_key),
    CONSTRAINT uk_employment_type_org_name UNIQUE (organization_id, type_name)
);

CREATE TABLE IF NOT EXISTS employment_status (
    employment_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    status_key VARCHAR(64) NOT NULL,
    status_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employment_status_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_employment_status_org_key UNIQUE (organization_id, status_key),
    CONSTRAINT uk_employment_status_org_name UNIQUE (organization_id, status_name)
);

CREATE TABLE IF NOT EXISTS employee (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    employee_code VARCHAR(64) NOT NULL,
    designation_id BIGINT NOT NULL,
    employment_type_id BIGINT NOT NULL,
    employment_status_id BIGINT NOT NULL,
    manager_employee_id BIGINT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    display_name VARCHAR(200),
    work_email VARCHAR(255) NOT NULL,
    personal_email VARCHAR(255),
    phone_number VARCHAR(32),
    joining_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    salary NUMERIC(14, 2),
    currency_code CHAR(3) DEFAULT 'USD',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_employee_designation
        FOREIGN KEY (designation_id) REFERENCES designation (designation_id),
    CONSTRAINT fk_employee_employment_type
        FOREIGN KEY (employment_type_id) REFERENCES employment_type (employment_type_id),
    CONSTRAINT fk_employee_employment_status
        FOREIGN KEY (employment_status_id) REFERENCES employment_status (employment_status_id),
    CONSTRAINT fk_employee_manager
        FOREIGN KEY (manager_employee_id) REFERENCES employee (employee_id),
    CONSTRAINT uk_employee_org_code UNIQUE (organization_id, employee_code),
    CONSTRAINT uk_employee_org_work_email UNIQUE (organization_id, work_email)
);

CREATE INDEX IF NOT EXISTS idx_employee_org_designation
    ON employee (organization_id, designation_id);

CREATE INDEX IF NOT EXISTS idx_employee_org_employment_type
    ON employee (organization_id, employment_type_id);

CREATE INDEX IF NOT EXISTS idx_employee_org_employment_status
    ON employee (organization_id, employment_status_id);

CREATE INDEX IF NOT EXISTS idx_employee_org_manager
    ON employee (organization_id, manager_employee_id);

CREATE TABLE IF NOT EXISTS team (
    team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    parent_team_id BIGINT NULL,
    team_code VARCHAR(64) NOT NULL,
    team_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_team_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_team_parent
        FOREIGN KEY (parent_team_id) REFERENCES team (team_id),
    CONSTRAINT uk_team_org_code UNIQUE (organization_id, team_code)
);

CREATE INDEX IF NOT EXISTS idx_team_org_name
    ON team (organization_id, team_name);

CREATE INDEX IF NOT EXISTS idx_team_org_parent
    ON team (organization_id, parent_team_id);

CREATE TABLE IF NOT EXISTS employee_team (
    employee_team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_team_employee
        FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_employee_team_team
        FOREIGN KEY (team_id) REFERENCES team (team_id),
    CONSTRAINT uk_employee_team UNIQUE (employee_id, team_id)
);

CREATE INDEX IF NOT EXISTS idx_employee_team_primary
    ON employee_team (team_id, is_primary);

CREATE TABLE IF NOT EXISTS resolver_group (
    resolver_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    parent_resolver_group_id BIGINT NULL,
    resolver_group_code VARCHAR(64) NOT NULL,
    resolver_group_name VARCHAR(120) NOT NULL,
    responsibility_scope VARCHAR(255),
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resolver_group_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_resolver_group_parent
        FOREIGN KEY (parent_resolver_group_id) REFERENCES resolver_group (resolver_group_id),
    CONSTRAINT uk_resolver_group_org_code UNIQUE (organization_id, resolver_group_code)
);

CREATE INDEX IF NOT EXISTS idx_resolver_group_org_name
    ON resolver_group (organization_id, resolver_group_name);

CREATE INDEX IF NOT EXISTS idx_resolver_group_org_parent
    ON resolver_group (organization_id, parent_resolver_group_id);

CREATE TABLE IF NOT EXISTS employee_resolver_group (
    employee_resolver_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    resolver_group_id BIGINT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_resolver_group_employee
        FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_employee_resolver_group_group
        FOREIGN KEY (resolver_group_id) REFERENCES resolver_group (resolver_group_id),
    CONSTRAINT uk_employee_resolver_group UNIQUE (employee_id, resolver_group_id)
);

CREATE INDEX IF NOT EXISTS idx_employee_resolver_group_primary
    ON employee_resolver_group (resolver_group_id, is_primary);

CREATE TABLE IF NOT EXISTS employee_resolver_group_exclusion (
    employee_resolver_group_exclusion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    resolver_group_id BIGINT NOT NULL,
    status exclusion_status NOT NULL DEFAULT 'ACTIVE',
    reason VARCHAR(255),
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_resolver_group_exclusion_employee
        FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_employee_resolver_group_exclusion_group
        FOREIGN KEY (resolver_group_id) REFERENCES resolver_group (resolver_group_id),
    CONSTRAINT uk_employee_resolver_group_exclusion UNIQUE (employee_id, resolver_group_id)
);

CREATE INDEX IF NOT EXISTS idx_employee_resolver_group_exclusion_group
    ON employee_resolver_group_exclusion (resolver_group_id);

CREATE INDEX IF NOT EXISTS idx_employee_resolver_group_exclusion_status
    ON employee_resolver_group_exclusion (employee_id, status);

CREATE TABLE IF NOT EXISTS permission_group (
    permission_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    parent_permission_group_id BIGINT NULL,
    permission_group_code VARCHAR(64) NOT NULL,
    permission_group_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_permission_group_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_permission_group_parent
        FOREIGN KEY (parent_permission_group_id) REFERENCES permission_group (permission_group_id),
    CONSTRAINT uk_permission_group_org_code UNIQUE (organization_id, permission_group_code),
    CONSTRAINT uk_permission_group_parent_name UNIQUE (organization_id, parent_permission_group_id, permission_group_name)
);

CREATE INDEX IF NOT EXISTS idx_permission_group_org_parent
    ON permission_group (organization_id, parent_permission_group_id);

CREATE TABLE IF NOT EXISTS employee_permission_group (
    employee_permission_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    permission_group_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_permission_group_employee
        FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_employee_permission_group_group
        FOREIGN KEY (permission_group_id) REFERENCES permission_group (permission_group_id),
    CONSTRAINT uk_employee_permission_group UNIQUE (employee_id, permission_group_id)
);

CREATE TABLE IF NOT EXISTS employee_permission_group_exclusion (
    employee_permission_group_exclusion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    permission_group_id BIGINT NOT NULL,
    status exclusion_status NOT NULL DEFAULT 'ACTIVE',
    reason VARCHAR(255),
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_permission_group_exclusion_employee
        FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_employee_permission_group_exclusion_group
        FOREIGN KEY (permission_group_id) REFERENCES permission_group (permission_group_id),
    CONSTRAINT uk_employee_permission_group_exclusion UNIQUE (employee_id, permission_group_id)
);

CREATE INDEX IF NOT EXISTS idx_employee_permission_group_exclusion_group
    ON employee_permission_group_exclusion (permission_group_id);

CREATE INDEX IF NOT EXISTS idx_employee_permission_group_exclusion_status
    ON employee_permission_group_exclusion (employee_id, status);

CREATE TABLE IF NOT EXISTS feature (
    feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key VARCHAR(80) NOT NULL UNIQUE,
    feature_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feature_permission (
    feature_permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id BIGINT NOT NULL,
    permission_key VARCHAR(64) NOT NULL,
    permission_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feature_permission_feature
        FOREIGN KEY (feature_id) REFERENCES feature (feature_id),
    CONSTRAINT uk_feature_permission_key UNIQUE (feature_id, permission_key)
);

CREATE TABLE IF NOT EXISTS permission_group_feature_permission (
    permission_group_feature_permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_group_id BIGINT NOT NULL,
    feature_permission_id BIGINT NOT NULL,
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pg_feature_permission_group
        FOREIGN KEY (permission_group_id) REFERENCES permission_group (permission_group_id),
    CONSTRAINT fk_pg_feature_permission_feature_permission
        FOREIGN KEY (feature_permission_id) REFERENCES feature_permission (feature_permission_id),
    CONSTRAINT uk_permission_group_feature_permission UNIQUE (permission_group_id, feature_permission_id)
);

CREATE TABLE IF NOT EXISTS ldap_directory (
    ldap_directory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    directory_code VARCHAR(64) NOT NULL,
    directory_name VARCHAR(120) NOT NULL,
    directory_type VARCHAR(64) NOT NULL,
    base_dn VARCHAR(255),
    server_uri VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ldap_directory_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_ldap_directory_code UNIQUE (organization_id, directory_code),
    CONSTRAINT uk_ldap_directory_name UNIQUE (organization_id, directory_name)
);

CREATE TABLE IF NOT EXISTS ldap_group (
    ldap_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_directory_id BIGINT NOT NULL,
    parent_ldap_group_id BIGINT NULL,
    external_group_key VARCHAR(128),
    group_dn VARCHAR(255) NOT NULL,
    group_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    synced_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ldap_group_directory
        FOREIGN KEY (ldap_directory_id) REFERENCES ldap_directory (ldap_directory_id),
    CONSTRAINT fk_ldap_group_parent
        FOREIGN KEY (parent_ldap_group_id) REFERENCES ldap_group (ldap_group_id),
    CONSTRAINT uk_ldap_group_dn UNIQUE (ldap_directory_id, group_dn),
    CONSTRAINT uk_ldap_group_external_key UNIQUE (ldap_directory_id, external_group_key)
);

CREATE INDEX IF NOT EXISTS idx_ldap_group_name
    ON ldap_group (ldap_directory_id, group_name);

CREATE INDEX IF NOT EXISTS idx_ldap_group_parent
    ON ldap_group (ldap_directory_id, parent_ldap_group_id);

CREATE TABLE IF NOT EXISTS ldap_user (
    ldap_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_directory_id BIGINT NOT NULL,
    external_user_key VARCHAR(128),
    user_dn VARCHAR(255) NOT NULL,
    username VARCHAR(120) NOT NULL,
    work_email VARCHAR(255),
    display_name VARCHAR(200),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    synced_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ldap_user_directory
        FOREIGN KEY (ldap_directory_id) REFERENCES ldap_directory (ldap_directory_id),
    CONSTRAINT uk_ldap_user_dn UNIQUE (ldap_directory_id, user_dn),
    CONSTRAINT uk_ldap_user_external_key UNIQUE (ldap_directory_id, external_user_key)
);

CREATE INDEX IF NOT EXISTS idx_ldap_user_username
    ON ldap_user (ldap_directory_id, username);

CREATE INDEX IF NOT EXISTS idx_ldap_user_work_email
    ON ldap_user (ldap_directory_id, work_email);

CREATE TABLE IF NOT EXISTS employee_ldap_identity (
    employee_ldap_identity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    ldap_user_id BIGINT NOT NULL,
    link_type ldap_identity_link_type NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    linked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unlinked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_ldap_identity_employee
        FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT fk_employee_ldap_identity_ldap_user
        FOREIGN KEY (ldap_user_id) REFERENCES ldap_user (ldap_user_id),
    CONSTRAINT uk_employee_ldap_identity_pair UNIQUE (employee_id, ldap_user_id),
    CONSTRAINT uk_employee_ldap_identity_ldap_user UNIQUE (ldap_user_id)
);

CREATE INDEX IF NOT EXISTS idx_employee_ldap_identity_employee_primary
    ON employee_ldap_identity (employee_id, is_primary);

CREATE TABLE IF NOT EXISTS ldap_user_group (
    ldap_user_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_user_id BIGINT NOT NULL,
    ldap_group_id BIGINT NOT NULL,
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ldap_user_group_user
        FOREIGN KEY (ldap_user_id) REFERENCES ldap_user (ldap_user_id),
    CONSTRAINT fk_ldap_user_group_group
        FOREIGN KEY (ldap_group_id) REFERENCES ldap_group (ldap_group_id),
    CONSTRAINT uk_ldap_user_group UNIQUE (ldap_user_id, ldap_group_id)
);

CREATE TABLE IF NOT EXISTS ldap_group_permission_group (
    ldap_group_permission_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_group_id BIGINT NOT NULL,
    permission_group_id BIGINT NOT NULL,
    mapped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ldap_group_permission_group_ldap_group
        FOREIGN KEY (ldap_group_id) REFERENCES ldap_group (ldap_group_id),
    CONSTRAINT fk_ldap_group_permission_group_permission_group
        FOREIGN KEY (permission_group_id) REFERENCES permission_group (permission_group_id),
    CONSTRAINT uk_ldap_group_permission_group UNIQUE (ldap_group_id, permission_group_id)
);

CREATE TABLE IF NOT EXISTS ldap_group_team (
    ldap_group_team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_group_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    mapped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ldap_group_team_ldap_group
        FOREIGN KEY (ldap_group_id) REFERENCES ldap_group (ldap_group_id),
    CONSTRAINT fk_ldap_group_team_team
        FOREIGN KEY (team_id) REFERENCES team (team_id),
    CONSTRAINT uk_ldap_group_team UNIQUE (ldap_group_id, team_id)
);

CREATE TABLE IF NOT EXISTS ldap_group_resolver_group (
    ldap_group_resolver_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_group_id BIGINT NOT NULL,
    resolver_group_id BIGINT NOT NULL,
    mapped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ldap_group_resolver_group_ldap_group
        FOREIGN KEY (ldap_group_id) REFERENCES ldap_group (ldap_group_id),
    CONSTRAINT fk_ldap_group_resolver_group_resolver_group
        FOREIGN KEY (resolver_group_id) REFERENCES resolver_group (resolver_group_id),
    CONSTRAINT uk_ldap_group_resolver_group UNIQUE (ldap_group_id, resolver_group_id)
);

CREATE TABLE IF NOT EXISTS plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code VARCHAR(40) NOT NULL UNIQUE,
    plan_name VARCHAR(120) NOT NULL,
    billing_period billing_period NOT NULL DEFAULT 'MONTHLY',
    base_price NUMERIC(12, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plan_feature (
    plan_feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    feature_id BIGINT NOT NULL,
    grant_type feature_grant_type NOT NULL DEFAULT 'DIRECT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_feature UNIQUE (plan_id, feature_id),
    CONSTRAINT fk_plan_feature_plan
        FOREIGN KEY (plan_id) REFERENCES plan (plan_id),
    CONSTRAINT fk_plan_feature_feature
        FOREIGN KEY (feature_id) REFERENCES feature (feature_id)
);

CREATE TABLE IF NOT EXISTS plan_feature_selection_rule (
    plan_feature_selection_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_feature_id BIGINT NOT NULL,
    applies_to_feature_id BIGINT NOT NULL,
    selection_scope selection_scope NOT NULL DEFAULT 'DIRECT_CHILDREN',
    min_selectable INT NOT NULL DEFAULT 0,
    max_selectable INT NOT NULL,
    selection_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_feature_selection_rule UNIQUE (plan_feature_id, applies_to_feature_id, selection_scope),
    CONSTRAINT fk_plan_feature_selection_rule_plan_feature
        FOREIGN KEY (plan_feature_id) REFERENCES plan_feature (plan_feature_id),
    CONSTRAINT fk_plan_feature_selection_rule_applies_to_feature
        FOREIGN KEY (applies_to_feature_id) REFERENCES feature (feature_id)
);

CREATE TABLE IF NOT EXISTS plan_feature_restriction (
    plan_feature_restriction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_feature_id BIGINT NOT NULL,
    restriction_key VARCHAR(80) NOT NULL,
    restriction_type restriction_type NOT NULL,
    restriction_operator restriction_operator NOT NULL,
    restriction_value VARCHAR(255) NOT NULL,
    restriction_unit restriction_unit,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_feature_restriction UNIQUE (plan_feature_id, restriction_key),
    CONSTRAINT fk_plan_feature_restriction_plan_feature
        FOREIGN KEY (plan_feature_id) REFERENCES plan_feature (plan_feature_id)
);

CREATE TABLE IF NOT EXISTS organization_feature_selection (
    organization_feature_selection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    feature_id BIGINT NOT NULL,
    status organization_feature_selection_status NOT NULL DEFAULT 'ACTIVE',
    selected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_org_feature_selection UNIQUE (organization_id, feature_id),
    CONSTRAINT fk_org_feature_selection_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_org_feature_selection_feature
        FOREIGN KEY (feature_id) REFERENCES feature (feature_id)
);

CREATE INDEX IF NOT EXISTS idx_org_feature_status
    ON organization_feature_selection (organization_id, status);

CREATE TABLE IF NOT EXISTS subscription (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NULL,
    status subscription_status NOT NULL DEFAULT 'PENDING',
    auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
    cancelled_at TIMESTAMP NULL,
    termination_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscription_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_subscription_plan
        FOREIGN KEY (plan_id) REFERENCES plan (plan_id)
);

CREATE INDEX IF NOT EXISTS idx_subscription_org_status_window
    ON subscription (organization_id, status, start_at, end_at);

CREATE TABLE IF NOT EXISTS coupon (
    coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code VARCHAR(64) NOT NULL UNIQUE,
    discount_type discount_type NOT NULL,
    discount_value NUMERIC(12, 2) NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    valid_to TIMESTAMP NULL,
    max_redemptions INT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS coupon_plan (
    coupon_plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_coupon_plan UNIQUE (coupon_id, plan_id),
    CONSTRAINT fk_coupon_plan_coupon
        FOREIGN KEY (coupon_id) REFERENCES coupon (coupon_id),
    CONSTRAINT fk_coupon_plan_plan
        FOREIGN KEY (plan_id) REFERENCES plan (plan_id)
);

CREATE TABLE IF NOT EXISTS subscription_coupon (
    subscription_coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    coupon_id BIGINT NOT NULL,
    applied_discount_value NUMERIC(12, 2) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_subscription_coupon UNIQUE (subscription_id, coupon_id),
    CONSTRAINT fk_subscription_coupon_subscription
        FOREIGN KEY (subscription_id) REFERENCES subscription (subscription_id),
    CONSTRAINT fk_subscription_coupon_coupon
        FOREIGN KEY (coupon_id) REFERENCES coupon (coupon_id)
);

-- Suggested seed examples (optional)
-- INSERT INTO feature (feature_id, feature_key, feature_name) VALUES
-- (1, 'TKT_PAGE', 'Ticket Page'),
-- (2, 'COMMENT_SECTION', 'Comment Section'),
-- (3, 'SUBJECT', 'Subject'),
-- (4, 'DESCRIPTION', 'Description'),
-- (5, 'AUTO_TKT_RESOLUTION', 'Auto Ticket Resolution'),
-- (6, 'COMMENT_RES', 'Comment Response'),
-- (7, 'AI_SUBJECT_SUMMARY', 'AI Subject Summary'),
-- (8, 'AUTH', 'Authentication'),
-- (9, 'AUTH_TYPE_OAUTH', 'OAuth Authentication'),
-- (10, 'AUTH_PROVIDER_GOOGLE', 'Google Provider');
--
-- INSERT INTO plan (plan_code, plan_name, billing_period, base_price, currency_code)
-- VALUES ('BASIC', 'Basic', 'MONTHLY', 0.00, 'USD');
--
-- Selection rule example:
-- BASIC + AUTH (SELECTABLE) => choose exactly 1 direct child auth type
--
-- Restriction example:
-- BASIC + COMMENT_SECTION => MAX_COMMENTS LTE 200 COUNT
