-- IMS subscription and feature schema
-- Target: PostgreSQL 17+
--
-- Hybrid storage note:
-- 1. PostgreSQL stores organization, subscription, plan, feature catalog,
--    plan entitlements, plan selection rules, restrictions, organization
--    selections, and coupons.
-- 2. MongoDB stores the feature adjacency graph only.
-- 3. Organization-owned employee taxonomy stays table-driven, not enum-driven,
--    so each organization can define its own designations, employment types,
--    and employment statuses.
--
-- Optional database creation (run separately as a superuser if needed):
-- CREATE DATABASE ims_subscription;
--
-- Then connect to the database before running the rest of this script.

-- Feature catalog examples:
-- 1  TKT_PAGE
-- 2  COMMENT_SECTION
-- 3  SUBJECT
-- 4  DESCRIPTION
-- 5  AUTO_TKT_RESOLUTION
-- 6  COMMENT_RES
-- 7  AI_SUBJECT_SUMMARY
-- 8  AUTH
-- 9  AUTH_TYPE_OAUTH
-- 10 AUTH_PROVIDER_GOOGLE
--
-- MongoDB adjacency examples:
-- 1  -> [2,3,4,5,7]
-- 2  -> [6]
-- 8  -> [9,11,12]
-- 9  -> [10,13,14]
-- 11 -> [15]

CREATE TYPE organization_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE domain_status AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE subscription_status AS ENUM ('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED');
CREATE TYPE billing_period AS ENUM ('MONTHLY', 'YEARLY');
CREATE TYPE discount_type AS ENUM ('PERCENTAGE', 'FIXED');
CREATE TYPE organization_feature_selection_status AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE restriction_type AS ENUM ('BOOLEAN', 'NUMERIC', 'TEXT', 'DURATION');
CREATE TYPE restriction_operator AS ENUM ('EQ', 'NE', 'LT', 'LTE', 'GT', 'GTE', 'IN');
CREATE TYPE restriction_unit AS ENUM ('COUNT', 'DAY', 'MINUTE', 'FLAG', 'CHARACTER', 'PERCENT');
CREATE TYPE selection_scope AS ENUM ('DIRECT_CHILDREN');
CREATE TYPE feature_grant_type AS ENUM ('DIRECT', 'SELECTABLE');

CREATE TABLE IF NOT EXISTS organization (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code VARCHAR(64) NOT NULL UNIQUE,
    organization_name VARCHAR(255) NOT NULL,
    status organization_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organization_domain (
    organization_domain_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    domain_name VARCHAR(320) NOT NULL UNIQUE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    status domain_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at TIMESTAMP NULL,
    CONSTRAINT fk_org_domain_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id)
);

CREATE INDEX IF NOT EXISTS idx_org_domain_primary
    ON organization_domain (organization_id, is_primary);

CREATE TABLE IF NOT EXISTS designation (
    designation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    designation_code VARCHAR(64),
    designation_title VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_designation_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_designation_org_title UNIQUE (organization_id, designation_title),
    CONSTRAINT uk_designation_org_code UNIQUE (organization_id, designation_code)
);

CREATE TABLE IF NOT EXISTS employment_type (
    employment_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    type_key VARCHAR(64) NOT NULL,
    type_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employment_type_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_employment_type_org_key UNIQUE (organization_id, type_key),
    CONSTRAINT uk_employment_type_org_name UNIQUE (organization_id, type_name)
);

CREATE TABLE IF NOT EXISTS employment_status (
    employment_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    status_key VARCHAR(64) NOT NULL,
    status_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employment_status_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT uk_employment_status_org_key UNIQUE (organization_id, status_key),
    CONSTRAINT uk_employment_status_org_name UNIQUE (organization_id, status_name)
);

CREATE TABLE IF NOT EXISTS employee (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    employee_code VARCHAR(64) NOT NULL,
    designation_id BIGINT NOT NULL,
    employment_type_id BIGINT NOT NULL,
    employment_status_id BIGINT NOT NULL,
    manager_employee_id BIGINT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    display_name VARCHAR(200),
    work_email VARCHAR(255) NOT NULL,
    personal_email VARCHAR(255),
    phone_number VARCHAR(32),
    joining_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    salary NUMERIC(14, 2),
    currency_code CHAR(3) DEFAULT 'USD',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_employee_designation
        FOREIGN KEY (designation_id) REFERENCES designation (designation_id),
    CONSTRAINT fk_employee_employment_type
        FOREIGN KEY (employment_type_id) REFERENCES employment_type (employment_type_id),
    CONSTRAINT fk_employee_employment_status
        FOREIGN KEY (employment_status_id) REFERENCES employment_status (employment_status_id),
    CONSTRAINT fk_employee_manager
        FOREIGN KEY (manager_employee_id) REFERENCES employee (employee_id),
    CONSTRAINT uk_employee_org_code UNIQUE (organization_id, employee_code),
    CONSTRAINT uk_employee_org_work_email UNIQUE (organization_id, work_email)
);

CREATE INDEX IF NOT EXISTS idx_employee_org_designation
    ON employee (organization_id, designation_id);

CREATE INDEX IF NOT EXISTS idx_employee_org_employment_type
    ON employee (organization_id, employment_type_id);

CREATE INDEX IF NOT EXISTS idx_employee_org_employment_status
    ON employee (organization_id, employment_status_id);

CREATE INDEX IF NOT EXISTS idx_employee_org_manager
    ON employee (organization_id, manager_employee_id);

CREATE TABLE IF NOT EXISTS feature (
    feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key VARCHAR(80) NOT NULL UNIQUE,
    feature_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code VARCHAR(40) NOT NULL UNIQUE,
    plan_name VARCHAR(120) NOT NULL,
    billing_period billing_period NOT NULL DEFAULT 'MONTHLY',
    base_price NUMERIC(12, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plan_feature (
    plan_feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    feature_id BIGINT NOT NULL,
    grant_type feature_grant_type NOT NULL DEFAULT 'DIRECT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_feature UNIQUE (plan_id, feature_id),
    CONSTRAINT fk_plan_feature_plan
        FOREIGN KEY (plan_id) REFERENCES plan (plan_id),
    CONSTRAINT fk_plan_feature_feature
        FOREIGN KEY (feature_id) REFERENCES feature (feature_id)
);

CREATE TABLE IF NOT EXISTS plan_feature_selection_rule (
    plan_feature_selection_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_feature_id BIGINT NOT NULL,
    applies_to_feature_id BIGINT NOT NULL,
    selection_scope selection_scope NOT NULL DEFAULT 'DIRECT_CHILDREN',
    min_selectable INT NOT NULL DEFAULT 0,
    max_selectable INT NOT NULL,
    selection_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_feature_selection_rule UNIQUE (plan_feature_id, applies_to_feature_id, selection_scope),
    CONSTRAINT fk_plan_feature_selection_rule_plan_feature
        FOREIGN KEY (plan_feature_id) REFERENCES plan_feature (plan_feature_id),
    CONSTRAINT fk_plan_feature_selection_rule_applies_to_feature
        FOREIGN KEY (applies_to_feature_id) REFERENCES feature (feature_id)
);

CREATE TABLE IF NOT EXISTS plan_feature_restriction (
    plan_feature_restriction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_feature_id BIGINT NOT NULL,
    restriction_key VARCHAR(80) NOT NULL,
    restriction_type restriction_type NOT NULL,
    restriction_operator restriction_operator NOT NULL,
    restriction_value VARCHAR(255) NOT NULL,
    restriction_unit restriction_unit,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_feature_restriction UNIQUE (plan_feature_id, restriction_key),
    CONSTRAINT fk_plan_feature_restriction_plan_feature
        FOREIGN KEY (plan_feature_id) REFERENCES plan_feature (plan_feature_id)
);

CREATE TABLE IF NOT EXISTS organization_feature_selection (
    organization_feature_selection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    feature_id BIGINT NOT NULL,
    status organization_feature_selection_status NOT NULL DEFAULT 'ACTIVE',
    selected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_org_feature_selection UNIQUE (organization_id, feature_id),
    CONSTRAINT fk_org_feature_selection_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_org_feature_selection_feature
        FOREIGN KEY (feature_id) REFERENCES feature (feature_id)
);

CREATE INDEX IF NOT EXISTS idx_org_feature_status
    ON organization_feature_selection (organization_id, status);

CREATE TABLE IF NOT EXISTS subscription (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NULL,
    status subscription_status NOT NULL DEFAULT 'PENDING',
    auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
    cancelled_at TIMESTAMP NULL,
    termination_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscription_org
        FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    CONSTRAINT fk_subscription_plan
        FOREIGN KEY (plan_id) REFERENCES plan (plan_id)
);

CREATE INDEX IF NOT EXISTS idx_subscription_org_status_window
    ON subscription (organization_id, status, start_at, end_at);

CREATE TABLE IF NOT EXISTS coupon (
    coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code VARCHAR(64) NOT NULL UNIQUE,
    discount_type discount_type NOT NULL,
    discount_value NUMERIC(12, 2) NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    valid_to TIMESTAMP NULL,
    max_redemptions INT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS coupon_plan (
    coupon_plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_coupon_plan UNIQUE (coupon_id, plan_id),
    CONSTRAINT fk_coupon_plan_coupon
        FOREIGN KEY (coupon_id) REFERENCES coupon (coupon_id),
    CONSTRAINT fk_coupon_plan_plan
        FOREIGN KEY (plan_id) REFERENCES plan (plan_id)
);

CREATE TABLE IF NOT EXISTS subscription_coupon (
    subscription_coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    coupon_id BIGINT NOT NULL,
    applied_discount_value NUMERIC(12, 2) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_subscription_coupon UNIQUE (subscription_id, coupon_id),
    CONSTRAINT fk_subscription_coupon_subscription
        FOREIGN KEY (subscription_id) REFERENCES subscription (subscription_id),
    CONSTRAINT fk_subscription_coupon_coupon
        FOREIGN KEY (coupon_id) REFERENCES coupon (coupon_id)
);

-- Suggested seed examples (optional)
-- INSERT INTO feature (feature_id, feature_key, feature_name) VALUES
-- (1, 'TKT_PAGE', 'Ticket Page'),
-- (2, 'COMMENT_SECTION', 'Comment Section'),
-- (3, 'SUBJECT', 'Subject'),
-- (4, 'DESCRIPTION', 'Description'),
-- (5, 'AUTO_TKT_RESOLUTION', 'Auto Ticket Resolution'),
-- (6, 'COMMENT_RES', 'Comment Response'),
-- (7, 'AI_SUBJECT_SUMMARY', 'AI Subject Summary'),
-- (8, 'AUTH', 'Authentication'),
-- (9, 'AUTH_TYPE_OAUTH', 'OAuth Authentication'),
-- (10, 'AUTH_PROVIDER_GOOGLE', 'Google Provider');
--
-- INSERT INTO plan (plan_code, plan_name, billing_period, base_price, currency_code)
-- VALUES ('BASIC', 'Basic', 'MONTHLY', 0.00, 'USD');
--
-- Selection rule example:
-- BASIC + AUTH (SELECTABLE) => choose exactly 1 direct child auth type
--
-- Restriction example:
-- BASIC + COMMENT_SECTION => MAX_COMMENTS LTE 200 COUNT
